image: maven:3-jdk-11

cache:
  paths:
    - .m2/repository
    
build:
    stage: build
    script:
       - mvn install
    artifacts:
        name: "wm-simulator-$CI_COMMIT_REF_NAME"
        paths:
            - target/soccer-simulation-0.0.1-SNAPSHOT.jar
        expire_in: 1 week    

