image: maven:3-jdk-11
variables:
    VERSION: '1.0'
cache:
  paths:
    - .m2/repository
    
build:
    stage: build
    script:
       - mvn install
    artifacts:
        name: "wm-simulator-$CI_COMMIT_REF_NAME"
        paths:
            - target/FIFA-WorldCupSim-$VERSION.jar
        expire_in: 1 week    

